# general settings
name: Enhancement_SGIENet_lol_gray_all_drconv_illum_sam_1018
model_type: ImageSamCleanModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedWithGrayIllumImage
    dataroot_gt: ./Enhancement/Datasets/our485/high
    dataroot_lq: ./Enhancement/Datasets/our485/low
    #dataroot_semantic: /data/liguanlin/codes/MIRNetv2/Enhancement/Datasets/our485/low_semantic_gray
    #dataroot_semantic: /data/liguanlin/codes/MIRNetv2/Enhancement/Datasets/our485/low_semantic_gray_sorted_reverted
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [4,2,2,1,1]             # Batch size per gpu   
    iters: [46000,32000,32000,28000,12000]
    gt_size: 384   # Max patch size for progressive training
    gt_sizes: [128,192,256,320,384]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [8]   
    # iters: [300000]
    # gt_size: 128   
    # gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedWithGrayIllumImage
    dataroot_gt: ./Enhancement/Datasets/eval15/high
    dataroot_lq: ./Enhancement/Datasets/eval15/low
    #dataroot_semantic: ./Enhancement/Datasets/eval15/low_semantic_gray
    #dataroot_semantic: ./Enhancement/Datasets/eval15/low_semantic_gray
    io_backend:
      type: disk

# network structures
network_g:
  type: SGIENetGrayAllDync
  img_channel: 3
  width: 32
  enc_blk_nums: [1, 1, 2, 2]
  middle_blk_num: 4
  dec_blk_nums: [1, 1, 2, 2]

# path
path:
  pretrain_network_g: ~ #"./experiments/Enhancement_NAF_lol_gray_sam_0907/models/net_g_74000.pth"
  strict_load_g: true
  resume_state: ~ #"./experiments/Enhancement_NAF_lol_gray_sam_0907/training_states/74000.state"

# training settings
train:
  total_iter: 150000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 16
  val_freq: !!float 1e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
